"""change name to username

Revision ID: 46341c64860d
Revises: 45efb522a7db
Create Date: 2023-08-03 09:26:59.688126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46341c64860d'
down_revision = '45efb522a7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.drop_column('org_name')
        batch_op.drop_column('org_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_email', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('org_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('username')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
