"""Add is_verified column to ngos

Revision ID: 5518dfb43d6d
Revises: 556085301fbb
Create Date: 2023-08-07 17:37:25.448823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5518dfb43d6d'
down_revision = '556085301fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
