"""Add is_verified column to donors

Revision ID: 556085301fbb
Revises: d0a191f4b31a
Create Date: 2023-08-07 17:13:37.708870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556085301fbb'
down_revision = 'd0a191f4b31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
