"""Add org_name column to ngo_donation_requests table

Revision ID: ca65441263eb
Revises: eed14f26111c
Create Date: 2023-08-03 11:37:35.205946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca65441263eb'
down_revision = 'eed14f26111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('org_email', sa.String(length=50), nullable=True))
        batch_op.drop_column('donor_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('donor_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('org_email')
        batch_op.drop_column('org_name')

    # ### end Alembic commands ###
