"""Add is_verified column

Revision ID: d0a191f4b31a
Revises: ca65441263eb
Create Date: 2023-08-07 15:18:32.519200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a191f4b31a'
down_revision = 'ca65441263eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
