"""Add donor_name column to donations table

Revision ID: eed14f26111c
Revises: 46341c64860d
Create Date: 2023-08-03 11:33:43.615846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed14f26111c'
down_revision = '46341c64860d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('username')

    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_donation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('donor_name')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('donor_name')

    # ### end Alembic commands ###
